### PR TITLE
update path to antigen.zsh

### PR DESCRIPTION
**Pull request by jippi**

### CODE REVIEW

**Comment by cassianoleal** [comment]
Hi @jippi,

Thanks for your contribution.

I'm sorry but I don't see how installing the `development` branch is sensible.

Perhaps make the source a parameter, defaulting to the stable release but allowing the user to override?

**Comment by jippi** [comment]
Sorry, the actual change the `bin/antigen` vs old `antigen` path, disregard the branch change i did by accident

**Comment by cassianoleal** [comment]
I see. Didn't know the path had changed. I'll be happy to merge this after you change it back to master. If you'd like I can just do the change myself as well.

**Comment by c10l** [comment]
I've released version 0.4.0 with this fixed and parameterised: https://github.com/cassianoleal/cookbook-zshell/commit/a2a526cd51a4b674e9874469dc27ef056cb2cfb8

Thanks for calling my attention to this and sending the pull request!

**Pull request closed without merging**
